package com.thecookiezen.recoverai.domain;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

import com.thecookiezen.recoverai.domain.SymptomInventory.SymptomResponse;

public class IntakeQuestions {

    private static final Map<SymptomCategory, List<String>> QUESTIONS = new EnumMap<>(SymptomCategory.class);

    static {
        QUESTIONS.put(SymptomCategory.DELUSION_OF_VELOCITY, List.of(
            "Is management measuring developer productivity by 'number of PRs' or 'lines of code' generated by AI?",
            "Are AI-generated features being pushed to production without a human code review?",
            "Has there been a formal directive to 'deprioritize unit tests' because 'the AI handles the logic'?"
        ));

        QUESTIONS.put(SymptomCategory.HALLUCINATORY_RESOURCE_PLANNING, List.of(
            "Has hiring been frozen specifically because leadership believes AI will double everyone's capacity by next quarter?",
            "Is management asking non-technical staff (Product Managers/Designers) to use 'natural language' AI tools to generate production code?",
            "Is there a 'we don't need senior devs' sentiment because 'the AI is the senior now'?"
        ));

        QUESTIONS.put(SymptomCategory.REALITY_DETACHMENT, List.of(
            "Is the company spending more on AI token/license costs than on the actual infrastructure or salaries needed to support them?",
            "When AI-generated code causes a production outage, is the blame shifted to 'bad prompting' rather than a flawed process?",
            "Are AI-related incidents being hidden or downplayed to maintain the narrative of AI success?"
        ));
    }

    public static Map<SymptomCategory, List<String>> getQuestions() {
        return QUESTIONS;
    }

    public static List<String> getQuestionsForCategory(SymptomCategory category) {
        return QUESTIONS.getOrDefault(category, List.of());
    }

    public static List<String> getAllQuestions() {
        return QUESTIONS.values().stream()
            .flatMap(List::stream)
            .toList();
    }

    public static SymptomInventory createInventory(List<SymptomResponse> responses) {
        Map<SymptomCategory, List<SymptomResponse>> categorized = new EnumMap<>(SymptomCategory.class);
        
        int index = 0;
        for (SymptomCategory category : SymptomCategory.values()) {
            List<String> categoryQuestions = QUESTIONS.get(category);
            List<SymptomResponse> categoryResponses = new ArrayList<>();
            for (int i = 0; i < categoryQuestions.size() && index < responses.size(); i++) {
                categoryResponses.add(responses.get(index));
                index++;
            }
            categorized.put(category, categoryResponses);
        }
        
        return new SymptomInventory(categorized);
    }
}
